name: Events Scraper Cron

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Run once daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run events scraper
        run: node events-scraper.js
        env:
          EVENTS_WEBHOOK_URL: ${{ secrets.EVENTS_WEBHOOK_URL }}

      - name: Configure Git
        run: |
          git config --global user.name '${{ secrets.GIT_USER_NAME }}'
          git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'

      - name: Commit and push if changed
        run: |
          git add events.json package-lock.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update events and dependencies" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}